notifications:
  email:
    on_success: never
    on_failure: change
  webhooks:
   urls:
     - https://webhooks.gitter.im/e/20782c6cada57d156a38
   on_success: never
   on_failure: always
   on_start: never

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 10

sudo: false

os:
  - os: linux
    dist: trusty
  - os: osx

env:
  global:
    - APM_TEST_PACKAGES=""

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

branches:
  only:
    - master
