version: "{build}"

platform: x64

branches:
    only:
      - master

clone_depth: 10

skip_tags: true

#notifications:
#  - provider: Webhook
#  - url: https://webhooks.gitter.im/e/e81e35dc4da288ca16ed

environment:
  APM_TEST_PACKAGES:

  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

install:
  - ps: Install-Product node 5

build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

test: off
deploy: off
